name: Terraform

on:
  push:
    branches: 
      - main
  workflow_dispatch: # Allows manual trigger of workflow for confirmation

permissions:
  contents: read

jobs:
  terraform:
    name: Terraform
    runs-on: self-hosted
    environment: production

    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4

      # Bypass PowerShell Execution Policy
      - name: Set PowerShell Execution Policy
        run: powershell.exe -ExecutionPolicy Bypass -Command "Set-ExecutionPolicy -Scope Process -ExecutionPolicy RemoteSigned -Force"

      # Initialize Terraform
      - name: Terraform Init
        run: terraform init

      # Plan Terraform changes
      - name: Terraform Plan
        env:
          TF_VAR_CONFLUENT_CLOUD_API_KEY: ${{ secrets.TF_VAR_CONFLUENT_CLOUD_API_KEY }}
          TF_VAR_CONFLUENT_CLOUD_API_SECRETS: ${{ secrets.TF_VAR_CONFLUENT_CLOUD_API_SECRETS }}
        run: terraform plan -out=tfplan

  apply:
    name: Apply Terraform
    needs: terraform
    runs-on: windows-latest
    environment: production

    steps:
      # Manual approval step
      - name: Require Approval
        uses: microsoft/pipelines-manual-approval-action@v1

      # Apply Terraform changes
      - name: Terraform Apply
        env:
          TF_VAR_CONFLUENT_CLOUD_API_KEY: ${{ secrets.TF_VAR_CONFLUENT_CLOUD_API_KEY }}
          TF_VAR_CONFLUENT_CLOUD_API_SECRETS: ${{ secrets.TF_VAR_CONFLUENT_CLOUD_API_SECRETS }}
        run: terraform apply -auto-approve tfplan

